server:
  port: 8880

dubbo:
  # 配置服务信息
  application:
    name: oomall-gateway
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://172.16.1.156:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: -1 # -1 表示端口自增 from 20880
    # 设置超时时间
    host: 172.16.0.254
  consumer:
    timeout: 4000
    check: false

spring:
  application:
    name: oomall-gateway
  cloud:
    nacos:
      discovery:
        ip: 172.16.0.254
        server-addr: 172.16.1.156:8848
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - HEAD
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: withoutToken
          uri: lb://user-service
          predicates:
            - Method=POST
            - Path=/users,/users/login
          filters:
            - PrefixPath=/other

        - id: userWithoutToken
          uri: lb://user-service
          predicates:
            - Path=/users/states
          filters:
            - PrefixPath=/other
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users,/users/password,/users/password/reset,/users/logout
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: footprint
          uri: lb://footprint-service
          predicates:
            - Path=
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: favorite
          uri: lb://favorite-service
          predicates:
            - Path=/favorites,/favorites/goods/{id},/favorites/{id}
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: advertiseWithoutToken
          uri: lb://advertise-service
          predicates:
            - Path=/advertisement/states,/advertisement/current
          filters:
            - PrefixPath=/other
        - id: advertise
          uri: lb://advertise-service
          predicates:
            - Path=
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: aftersaleWithoutToken
          uri: lb://aftersale-service
          predicates:
            - Path=/aftersales/states
          filters:
            - PrefixPath=/other
        - id: aftersale
          uri: lb://aftersale-service
          predicates:
            - Path=/orderitems/{id}/aftersales,/aftersales,/aftersales/{id},/aftersales/{id}/sendback,/aftersales/{id}/confirm
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: addressWithoutToken
          uri: lb://address-service
          predicates:
            - Path=/region/{id}/ancestor
          filters:
            - PrefixPath=/other
        - id: address
          uri: lb://address-service
          predicates:
            - Path=/addresses,/addresses/{id},/addresses/{id}/default,/region/{id}/ancestor
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts,/carts/{id}
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: share
          uri: lb://share-service
          predicates:
            - Path=/skus/{id}/shares,/shares,/beshared,/shareactivities
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: orderWithoutToken
          uri: lb://order-service
          predicates:
            - Path=/orders/states
          filters:
            - PrefixPath=/order
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/orders,/orders/{id},/orders/{id}/confirm,/orders/{id}/groupon-normal
          filters:
            - PrefixPath=/order
            - Auth=authorization

        - id: freight
          uri: lb://freight-service
          predicates:
            - Path=/region/{rid}/price,
          filters:
            - PrefixPath=/order
            - Auth=authorization

        - id: paymentWithoutToken
          uri: lb://payment-service
          predicates:
            - Path=/payments/states,/payments/patterns
          filters:
            - PrefixPath=/order

        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/orders/{id}/payments,/aftersales/{id}/payments,/orders/{id}/refunds,/aftersales/{id}/refunds
          filters:
            - PrefixPath=/order
            - Auth=authorization

        - id: goodsWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/skus/states,/skus,/skus/{id},/categories/{id}/subcategories,/spus/{id},/brands
          filters:
            - PrefixPath=/goods
        - id: goods
          uri: lb://g12service
          predicates:
            - Path=/share/{sid}/skus/{id}
          filters:
            - PrefixPath=/goods
            - Auth=authorization

        - id: time
          uri: lb://time-service
          predicates:
            - Path=
          filters:
            - PrefixPath=/other
            - Auth=authorization

        - id: flashsaleWithoutToken
          uri: lb://g12service
          predicates:
            - Method=GET
            - Path=/timesegments/{id}/flashsales,/flashsales/current
          filters:
            - PrefixPath=/goods

        - id: commentWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/comments/states,/skus/{id}/comments
          filters:
            - PrefixPath=/goods
        - id: comment
          uri: lb://g12service
          predicates:
            - Path=/comments,/orderitems/{id}/comments
          filters:
            - PrefixPath=/goods
            - Auth=authorization

        - id: couponWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/coupons/states,/couponactivities,/couponactivities/{id}/skus
          filters:
            - PrefixPath=/goods
        - id: coupon
          uri: lb://g12service
          predicates:
            - Path=/coupons,/couponactivities/{id}/usercoupons
          filters:
            - PrefixPath=/goods
            - Auth=authorization

        - id: presaleWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/presales/states,/presales
          filters:
            - PrefixPath=/goods

        - id: grouponWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/groupons/states
          filters:
            - PrefixPath=/goods
        - id: groupon
          uri: lb://g12service
          predicates:
            - Path=/groupons
          filters:
            - PrefixPath=/goods
            - Auth=authorization

        - id: shopWithoutToken
          uri: lb://g12service
          predicates:
            - Path=/shops/states
          filters:
            - PrefixPath=/goods

  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    #    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000


management:
  endpoint:
    gateway:
      enabled: true

# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 172.16.4.31:9876
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2

# 网关token相关配置
privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60